package golem:demo;

// See https://component-model.bytecodealliance.org/design/wit.html for more details about the WIT syntax

interface api {

  variant actions {
    register(string),
    follow(string),
    unfollow(string),
    post-tweet(string)
  }

  variant custom-result {
    success(string),
    failure(string)
  }

  add: func(value: u64);
  get: func(actions: actions, user-id: string) -> custom-result;
  remote: func(input: string) -> result<string, string>;
}

world example {
  export api;
}
